
EINSTEIN_BASE_URL = 'https://api.einstein.ai/v2'
VISION_BASE_URL = EINSTEIN_BASE_URL + '/vision'
DATASETS_URL = VISION_BASE_URL + '/datasets'
VISION_MODEL_URL = VISION_BASE_URL + '/models'
VISION_PREDICT_URL = VISION_BASE_URL + '/predict'
VISION_DETECT_URL = VISION_BASE_URL + '/detect'

LANG_BASE_URL = EINSTEIN_BASE_URL + '/language'
LANG_DATASETS_URL = LANG_BASE_URL + '/datasets'
LANG_MODEL_URL = LANG_BASE_URL + '/models'
LANG_INTENT_PREDICT_URL = LANG_BASE_URL + '/intent'
LANG_SENTIMENT_PREDICT_URL = LANG_BASE_URL + '/sentiment'

ACCESS_TOKEN = ''

