
EINSTEIN_BASE_URL = 'https://api.einstein.ai/v2'
VISION_BASE_URL = EINSTEIN_BASE_URL + '/vision'
DATASETS_URL = VISION_BASE_URL + '/datasets'
VISION_MODEL_URL = VISION_BASE_URL + '/models'
VISION_PREDICT_URL = VISION_BASE_URL + '/predict'

ACCESS_TOKEN = ''
