
EINSTEIN_BASE_URL = 'https://api.einstein.ai/v2'
VISION_BASE_URL = EINSTEIN_BASE_URL + '/vision'
DATASETS_URL = VISION_BASE_URL + '/datasets'
VISION_MODEL_URL = VISION_BASE_URL + '/models'
VISION_PREDICT_URL = VISION_BASE_URL + '/predict'
VISION_DETECT_URL = VISION_BASE_URL + '/detect'

LANG_BASE_URL = EINSTEIN_BASE_URL + '/language'
LANG_DATASETS_URL = LANG_BASE_URL + '/datasets'
LANG_MODEL_URL = LANG_BASE_URL + '/models'
LANG_INTENT_PREDICT_URL = LANG_BASE_URL + '/intent'
LANG_SENTIMENT_PREDICT_URL = LANG_BASE_URL + '/sentiment'

TYPE_IMAGE = "image"
TYPE_IMAGE_DETECTION = "image-detection"
TYPE_IMAGE_MULTILABEL = "image-multi-label"

ACCESS_TOKEN = 'ec7b4b22ea6e423ff87780d4f56b65c206395b48'

